### ISSUE TITLE
Regarding the running time limit (Sprint 2)

### ISSUE THREAD

**Issue by heywrcoding** [drivendataorg/deid2-runtime#31]
Hello,

We are aware that there is a running time limit requirement (under 3 hrs) for code submissions to this challenge. Unfortunately, due to the deep learning nature of our pre-screened method, our code may need to take significantly more time than this to produce reasonable results. From our testing, the hyper-parameter selection that leads to the best results required over 2 days of training on our machines. 

While we understand that requesting resources to that degree would be unfair, we would like to ask if we could have any additional running time for our approach? If we know in advance what the upper bound on the runtime would be, we can set our hyperparameter values such that it will likely finish in that time frame.

Thank you,
Goose-DP2

**Comment by isms** [comment]
Hi @heywrcoding, just to be clear you are not actually training the model in this runtime container, right?

**Comment by mshubhankar** [comment]
Our current approach will require some training on the private data in the runtime container. We would like clarification on the upper bound of the allowed runtime, so that we can try and set appropriate parameter values that will allow our approach to finish in the allotted time. 
If model training is not permitted in the runtime container at all, please let us know.
Thanks, 
GooseDP-2

**Comment by isms** [comment]
@mshubhankar Understood, we are bumping runtime limit to 12h. To ensure fastest response from here on out, please email us directly at info@drivendata.org if there are any further questions.
